---
# These are supported funding model platforms.

github:  # Up to four GitHub Sponsors-enabled usernames.
patreon:  # A single Patreon username.
open_collective:  # A single Open Collective username.
ko_fi:  # A single Ko-fi username.
tidelift:  # A Tidelift platform-name/package-name.
community_bridge:  # A single Community Bridge project name.
liberapay:  # A single Liberapay username.
issuehunt:  # A single IssueHunt username.
lfx_crowdfunding:  # A single LFX Crowdfunding project name.
polar:  # A single Polar username.
buy_me_a_coffee:  # A single Buy Me a Coffee username.
thanks_dev:  # A single thanks.dev username.
